-- ============================================================================
-- 0001 - Esquema del Sistema Inteligente de Ventas
--
-- Modelo de ofertas preconfiguradas. La emocion detectada NO calcula el
-- descuento: solo decide si el sistema se queda donde esta o avanza al
-- siguiente escalon de una secuencia que una persona definio antes
-- (docs/REGLAS_DE_NEGOCIO.md). El descuento vive en la base, no en el codigo.
--
-- Tres diferencias frente al diseno que se envio en schema-bd.sql, todas
-- deliberadas y todas con la misma razon de fondo: la clave anonima viaja
-- DENTRO del APK y cualquiera puede extraerla.
--
--   1. El dinero es INTEGER en centavos, no DECIMAL(10,2). En PostgreSQL
--      DECIMAL es exacto, pero PostgREST lo serializa a JSON y Dart lo recibe
--      como double: 2500.00 -> 2499.9999999999995 en cuanto se multiplica por
--      un porcentaje. Guardando centavos enteros la aritmetica monetaria
--      nunca toca punto flotante, ni aqui ni en la app.
--
--   2. Toda tabla tiene RLS y la app solo puede LEER. Las escrituras pasan por
--      funciones SECURITY DEFINER (0002_funciones.sql) que validan las reglas
--      del negocio. Sin esto, quien extraiga la clave del APK puede hacer
--      `update productos set precio_centavos = 0`.
--
--   3. El porcentaje de descuento es un entero 1..90, no un DECIMAL 0..1.
--      Un tope de 90 evita regalar el producto; el 0..1 del diseno original
--      permitia 1.00 (100%) y dejaba el total en 0, ensuciando cualquier
--      reporte de monto. Entero ademas porque 0.10 en binario no es 0.10.
-- ============================================================================

-- --------------- ROLES ---------------
--
-- Supabase los trae de fabrica; un PostgreSQL pelado no. Se crean aqui para
-- que la misma migracion corra igual en la nube, en el contenedor local y en
-- CI. `nologin`: son roles de permisos, no cuentas. Quien los asume es
-- PostgREST segun el token que traiga la peticion.
do $do$
begin
  if not exists (select 1 from pg_roles where rolname = 'anon') then
    create role anon nologin noinherit;
  end if;
  if not exists (select 1 from pg_roles where rolname = 'authenticated') then
    create role authenticated nologin noinherit;
  end if;
  if not exists (select 1 from pg_roles where rolname = 'service_role') then
    create role service_role nologin noinherit bypassrls;
  end if;
end
$do$;

grant usage on schema public to anon, authenticated, service_role;

-- --------------- 1. CLIENTES ---------------

create table if not exists clientes (
  id_cliente bigint generated by default as identity primary key,
  nombre     varchar(255) not null,
  paterno    varchar(255),
  materno    varchar(255),
  telefono   varchar(20),
  correo     varchar(255),
  creado_en  timestamptz not null default now()
);

-- --------------- 2. CATEGORIAS ---------------

create table if not exists categorias (
  id_categoria bigint generated by default as identity primary key,
  nombre       varchar(255) not null unique
);

-- --------------- 3. MARCAS ---------------

create table if not exists marcas (
  id_marca bigint generated by default as identity primary key,
  nombre   varchar(255) not null unique
);

-- --------------- 4. PRODUCTOS ---------------

create table if not exists productos (
  id_producto    bigint generated by default as identity primary key,
  id_categoria   bigint not null references categorias(id_categoria),
  id_marca       bigint not null references marcas(id_marca),
  nombre         varchar(255) not null,
  descripcion    varchar(255),

  -- Centavos enteros (ver nota 1 de la cabecera). S/2500.00 se guarda 250000.
  precio_centavos integer not null check (precio_centavos >= 0),

  stock          integer not null default 0 check (stock >= 0),

  -- Nombre de archivo en assets/products/ o URL completa.
  imagen         varchar(255),
  fecha_registro timestamptz not null default now(),
  activo         boolean not null default true
);

-- El catalogo se lee filtrando por activo y stock en cada carga.
create index if not exists ix_productos_disponibles
  on productos (activo, stock) where activo and stock > 0;

-- --------------- 5. ADMINISTRADORES ---------------
--
-- Quien publica ofertas. La FK contra auth.users se agrega solo si ese
-- esquema existe, para que la migracion corra igual en un Postgres pelado.

create table if not exists administradores (
  id_admin bigint generated by default as identity primary key,
  nombre   varchar(255) not null,
  apellido varchar(255) not null,
  telefono varchar(20),
  correo   varchar(255),
  -- Enlace opcional con la cuenta de Supabase que opera el panel.
  uid      uuid unique
);

do $do$
begin
  if exists (select 1 from information_schema.schemata where schema_name = 'auth')
     and not exists (
       select 1 from information_schema.table_constraints
        where constraint_name = 'fk_administradores_uid'
     )
  then
    alter table administradores
      add constraint fk_administradores_uid
      foreign key (uid) references auth.users(id) on delete set null;
  end if;
end
$do$;

-- --------------- 6. TIPOS DE OFERTA ---------------

create table if not exists tipos_oferta (
  id_tipo bigint generated by default as identity primary key,
  nombre  varchar(255) not null unique
);

-- --------------- 7. OFERTAS ---------------
--
-- Una oferta es de descuento (porcentaje) o de combo (precio final fijo),
-- nunca de las dos cosas ni de ninguna: lo garantiza chk_oferta_coherente.
-- El diseno original dejaba pasar una oferta con los dos campos en NULL, que
-- no significa nada y rompe el calculo del precio.

create table if not exists ofertas (
  id_oferta bigint generated by default as identity primary key,
  id_admin  bigint not null references administradores(id_admin),
  nombre    varchar(255) not null,
  id_tipo   bigint not null references tipos_oferta(id_tipo),

  -- Entero 1..90 (ver nota 3). 20 = 20% de descuento.
  porcentaje_descuento integer
    check (porcentaje_descuento is null
           or porcentaje_descuento between 1 and 90),

  -- Precio final del combo, en centavos.
  precio_oferta_centavos integer
    check (precio_oferta_centavos is null or precio_oferta_centavos >= 0),

  activa       boolean not null default true,
  fecha_inicio timestamptz not null default now(),
  fecha_fin    timestamptz,

  check (fecha_fin is null or fecha_fin > fecha_inicio),

  -- Exactamente uno de los dos: o rebaja un porcentaje, o fija un precio.
  constraint chk_oferta_coherente check (
    (porcentaje_descuento is not null and precio_oferta_centavos is null)
    or
    (porcentaje_descuento is null and precio_oferta_centavos is not null)
  )
);

-- --------------- 8. OFERTAS_PRODUCTOS ---------------
--
-- Que oferta corresponde a que producto y en que posicion de la secuencia.
-- `orden` vive aqui y no en `ofertas` porque la misma oferta puede ocupar
-- distinta posicion segun el producto.

create table if not exists ofertas_productos (
  id_oferta_producto bigint generated by default as identity primary key,
  id_oferta   bigint not null references ofertas(id_oferta) on delete cascade,
  id_producto bigint not null references productos(id_producto) on delete cascade,
  orden       integer not null check (orden > 0),
  cantidad    integer not null default 1 check (cantidad > 0),

  -- Dos ofertas no pueden pelear por el mismo escalon del mismo producto: el
  -- desempate seria arbitrario y la secuencia dejaria de ser reproducible.
  constraint uq_orden_por_producto unique (id_producto, orden),

  -- Y la misma oferta no se repite sobre el mismo producto.
  constraint uq_oferta_producto unique (id_oferta, id_producto)
);

create index if not exists ix_ofertas_productos_secuencia
  on ofertas_productos (id_producto, orden);

-- --------------- 9. VENTA ---------------

create table if not exists venta (
  id_venta bigint generated by default as identity primary key,

  -- NULL cuando la compra fue a precio normal, sin oferta.
  id_oferta  bigint references ofertas(id_oferta),
  id_cliente bigint not null references clientes(id_cliente),

  subtotal_centavos  integer not null check (subtotal_centavos >= 0),
  descuento_centavos integer not null default 0 check (descuento_centavos >= 0),
  total_centavos     integer not null check (total_centavos >= 0),

  -- Es lo que permite contar las compras del dia para el limite de ofertas.
  fecha_hora timestamptz not null default now(),

  -- El total tiene que cuadrar: si no, el reporte miente y nadie se entera.
  constraint chk_venta_cuadra
    check (total_centavos = subtotal_centavos - descuento_centavos)
);

create index if not exists ix_venta_cliente_fecha
  on venta (id_cliente, fecha_hora desc);

-- --------------- 10. DETALLE_VENTA ---------------

create table if not exists detalle_venta (
  id_detalle_venta bigint generated by default as identity primary key,
  id_venta    bigint not null references venta(id_venta) on delete cascade,
  id_producto bigint not null references productos(id_producto),
  cantidad    integer not null check (cantidad > 0),

  -- Precio congelado: lo que el cliente pago por esta linea, no el precio
  -- que el producto tenga hoy.
  precio_total_centavos integer not null check (precio_total_centavos >= 0)
);

create index if not exists ix_detalle_venta_venta
  on detalle_venta (id_venta);

-- ============================================================================
-- SEGURIDAD (RLS)
--
-- La app lee el catalogo y nada mas. No puede insertar ni actualizar ninguna
-- tabla: las tres escrituras que necesita pasan por funciones validadas en
-- 0002_funciones.sql. Que no pueda hacer INSERT no es decorativo — si pudiera,
-- tambien podria hacer UPDATE de precios, y la clave esta dentro del APK.
-- ============================================================================

alter table clientes          enable row level security;
alter table categorias        enable row level security;
alter table marcas            enable row level security;
alter table productos         enable row level security;
alter table administradores   enable row level security;
alter table tipos_oferta      enable row level security;
alter table ofertas           enable row level security;
alter table ofertas_productos enable row level security;
alter table venta             enable row level security;
alter table detalle_venta     enable row level security;

-- Lectura publica: lo que la tienda necesita mostrar.
do $do$
declare t text;
begin
  foreach t in array array[
    'categorias','marcas','productos','tipos_oferta','ofertas','ofertas_productos'
  ]
  loop
    execute format(
      'drop policy if exists p_lectura_publica on %I', t);
    execute format(
      'create policy p_lectura_publica on %I for select to anon, authenticated using (true)', t);
  end loop;
end
$do$;

-- Clientes, ventas y detalle NO son de lectura publica: contienen datos
-- personales y el historial de compra de otras personas. La app los consulta
-- a traves de funciones que solo devuelven lo del cliente en curso.

-- Administradores autenticados: gestion del catalogo y las ofertas desde el
-- panel. `service_role` (el panel de Supabase) ignora RLS por definicion.
--
-- `auth.uid()` solo existe en Supabase. En un PostgreSQL pelado (el contenedor
-- de desarrollo, el de CI) no hay esquema `auth`, y crear la politica fallaria
-- con `schema "auth" does not exist`. Ahi se omite: no hay usuarios que
-- autenticar, las pruebas usan `set role` y el dueno de la base ignora RLS.
do $do$
declare t text;
begin
  if not exists (select 1 from information_schema.schemata where schema_name = 'auth') then
    raise notice 'Sin esquema auth: se omiten las politicas de administrador (normal fuera de Supabase)';
    return;
  end if;

  foreach t in array array[
    'categorias','marcas','productos','tipos_oferta','ofertas','ofertas_productos'
  ]
  loop
    execute format('drop policy if exists p_admin_escribe on %I', t);
    execute format($f$
      create policy p_admin_escribe on %I for all to authenticated
        using (exists (select 1 from administradores a where a.uid = auth.uid()))
        with check (exists (select 1 from administradores a where a.uid = auth.uid()))
    $f$, t);
  end loop;
end
$do$;

-- Permisos de tabla. RLS filtra filas; los GRANT deciden que verbos existen.
grant select on categorias, marcas, productos, tipos_oferta, ofertas,
                ofertas_productos to anon, authenticated;

grant select, insert, update, delete
  on categorias, marcas, productos, tipos_oferta, ofertas, ofertas_productos
  to authenticated;

-- Nada de acceso directo a datos personales ni a ventas.
revoke all on clientes, administradores, venta, detalle_venta from anon;
