-- ============================================================================
-- 0003 - Catalogo de demostracion
--
-- Los datos de llenado-datos.sql, con dos cambios:
--
--   1. Sin TRUNCATE. El original empezaba borrando diez tablas en cascada;
--      aplicado por equivocacion sobre una base con ventas reales, no hay
--      vuelta atras. Aqui cada insert es idempotente (`on conflict do
--      nothing`), asi que correr la semilla dos veces no duplica ni borra
--      nada. Para vaciar la base a proposito esta supabase/tests/limpiar.sql,
--      que hay que ejecutar a mano.
--
--   2. Precios en centavos enteros: 2500.00 -> 250000. Ver la nota 1 de
--      0001_esquema.sql.
--
-- Los IDs no se fuerzan: las columnas son `generated by default as identity`
-- y fijarlos a mano deja la secuencia atras, de modo que el primer producto
-- que cree el administrador desde el panel chocaria con la clave primaria.
-- Las relaciones se resuelven por nombre.
-- ============================================================================

-- --------------- CATEGORIAS ---------------

insert into categorias (nombre) values
  ('Laptops'), ('Celulares'), ('Accesorios'), ('Audifonos')
on conflict (nombre) do nothing;

-- --------------- MARCAS ---------------

insert into marcas (nombre) values
  ('Lenovo'), ('HP'), ('Samsung'), ('Logitech'), ('Sony')
on conflict (nombre) do nothing;

-- --------------- TIPOS DE OFERTA ---------------

insert into tipos_oferta (nombre) values
  ('Descuento'), ('Combo')
on conflict (nombre) do nothing;

-- --------------- ADMINISTRADORES ---------------
--
-- `uid` queda en NULL: se enlaza con la cuenta real de Supabase cuando esa
-- persona entra por primera vez al panel (Authentication -> Users).

insert into administradores (nombre, apellido, telefono, correo)
select 'Steven', 'Cadillo', '999111222', 'steven@tienda.com'
 where not exists (select 1 from administradores where correo = 'steven@tienda.com');

insert into administradores (nombre, apellido, telefono, correo)
select 'Luis', 'Garcia', '999222333', 'luis@tienda.com'
 where not exists (select 1 from administradores where correo = 'luis@tienda.com');

-- --------------- CLIENTES DE PRUEBA ---------------

insert into clientes (nombre, paterno, materno, telefono, correo)
select v.* from (values
  ('Juan',   'Perez',    'Gomez',  '987654321', 'juan@gmail.com'),
  ('Maria',  'Lopez',    'Torres', '986543210', 'maria@gmail.com'),
  ('Carlos', 'Ramirez',  'Flores', '985432109', 'carlos@gmail.com'),
  ('Ana',    'Martinez', 'Rojas',  '984321098', 'ana@gmail.com')
) as v(nombre, paterno, materno, telefono, correo)
where not exists (select 1 from clientes c where c.correo = v.correo);

-- --------------- PRODUCTOS ---------------
--
-- Precios en centavos: S/2500.00 = 250000.

-- Sin imagen: cada producto muestra el icono de su categoria hasta que el
-- administrador suba una foto al bucket `productos` (ver 0005). Sembrar
-- nombres de archivo aqui solo servia para que la app pidiera 404s.
insert into productos (id_categoria, id_marca, nombre, descripcion,
                       precio_centavos, stock)
select c.id_categoria, m.id_marca, v.nombre, v.descripcion,
       v.precio_centavos, v.stock
  from (values
    ('Laptops',    'Lenovo',   'Laptop Lenovo IdeaPad',
     'Laptop para uso academico y oficina',  250000, 10),
    ('Laptops',    'HP',       'Laptop HP Pavilion',
     'Laptop para trabajo y estudio',        280000,  8),
    ('Celulares',  'Samsung',  'Samsung Galaxy A55',
     'Smartphone Samsung Galaxy',            150000, 15),
    ('Accesorios', 'Logitech', 'Mouse Logitech G203',
     'Mouse gamer',                           12000, 30),
    ('Accesorios', 'Logitech', 'Teclado Logitech K380',
     'Teclado inalambrico',                   18000, 20),
    ('Audifonos',  'Sony',     'Audifonos Sony WH-CH520',
     'Audifonos inalambricos',                25000, 12)
  ) as v(categoria, marca, nombre, descripcion, precio_centavos, stock)
  join categorias c on c.nombre = v.categoria
  join marcas     m on m.nombre = v.marca
 where not exists (select 1 from productos p where p.nombre = v.nombre);

-- --------------- OFERTAS ---------------
--
-- Porcentajes enteros: 10 = 10%. Los combos fijan el precio final en centavos.

insert into ofertas (id_admin, nombre, id_tipo, porcentaje_descuento,
                     precio_oferta_centavos, fecha_inicio, fecha_fin)
select a.id_admin, v.nombre, t.id_tipo, v.pct, v.precio,
       timestamptz '2026-09-01 00:00:00-05', timestamptz '2026-12-31 23:59:59-05'
  from (values
    ('steven@tienda.com', 'Descuento 10%', 'Descuento',   10, null::integer),
    ('steven@tienda.com', 'Descuento 20%', 'Descuento',   20, null),
    ('luis@tienda.com',   'Descuento 30%', 'Descuento',   30, null),
    ('luis@tienda.com',   'Combo Gamer',   'Combo',     null, 20000),
    ('steven@tienda.com', 'Combo Audio',   'Combo',     null, 35000)
  ) as v(correo, nombre, tipo, pct, precio)
  join administradores a on a.correo = v.correo
  join tipos_oferta    t on t.nombre = v.tipo
 where not exists (select 1 from ofertas o where o.nombre = v.nombre);

-- --------------- SECUENCIA DE OFERTAS POR PRODUCTO ---------------
--
-- El orden es la escalera por la que sube el sistema cuando la respuesta del
-- cliente es desfavorable: primero 10%, luego 20%, luego 30%. Un producto sin
-- filas aqui se queda siempre en su precio normal (README, regla 8).

insert into ofertas_productos (id_oferta, id_producto, orden, cantidad)
select o.id_oferta, p.id_producto, v.orden, v.cantidad
  from (values
    -- Laptop Lenovo: escalera completa de tres escalones
    ('Descuento 10%', 'Laptop Lenovo IdeaPad',   1, 1),
    ('Descuento 20%', 'Laptop Lenovo IdeaPad',   2, 1),
    ('Descuento 30%', 'Laptop Lenovo IdeaPad',   3, 1),

    -- Samsung Galaxy: dos escalones
    ('Descuento 10%', 'Samsung Galaxy A55',      1, 1),
    ('Descuento 20%', 'Samsung Galaxy A55',      2, 1),

    -- Mouse: un solo escalon de descuento, y ademas entra en el combo
    ('Descuento 10%', 'Mouse Logitech G203',     1, 1),
    ('Combo Gamer',   'Mouse Logitech G203',     2, 1),
    ('Combo Gamer',   'Teclado Logitech K380',   1, 1),

    -- Combo Audio
    ('Combo Audio',   'Audifonos Sony WH-CH520', 1, 1)
  ) as v(oferta, producto, orden, cantidad)
  join ofertas   o on o.nombre = v.oferta
  join productos p on p.nombre = v.producto
 where not exists (
   select 1 from ofertas_productos op
    where op.id_oferta = o.id_oferta and op.id_producto = p.id_producto
 );

-- Nota sobre los datos de venta del archivo original: no se siembran. Las
-- ventas las crea fn_registrar_venta, que descuenta stock y valida el limite
-- diario; insertarlas a mano dejaria el stock descuadrado respecto de lo
-- vendido y el limite de dos ofertas por dia consumido desde el primer
-- arranque. Para probar el ciclo completo estan las pruebas SQL.
--
-- La Laptop HP Pavilion queda a proposito sin ofertas: es el caso de la regla
-- 8 (producto sin oferta -> se mantiene el precio normal) y conviene tenerlo
-- en el catalogo de demostracion.
